user:
    resource: "@UserBundle/Resources/config/routing.yml"
    prefix:   /users

admin:
    resource: "@AdminBundle/Resources/config/routing.yml"
    prefix:   /admin

core:
    resource: "@CoreBundle/Resources/config/routing.yml"
    prefix:   /


